In [2]:
import pandas as pd
df=pd.read_csv('flipkart_pricing.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: 'flipkart_pricing.csv'

In [14]:
print(df.dtypes)

company_name        object
product_name        object
category            object
price               object
discount_percent    object
date                object
dtype: object

In [13]:
print(df['price'].unique())
print(df['price'].dtype)

[39999.     0.   267.   194.   311.   293.   670.   430.   348.   297.
   300.   405.   339.   397.   203.   166.   249.   244. 31990.   135.
   138.  1099.   505.   400.   807.   264.   131.   526.   581.]
float64

In [15]:
df['price']=df['price'].str.replace(',','')
df['price']=pd.to_numeric(df['price'],errors='coerce')
df['price']=df['price'].fillna(0)
df

,company_name,product_name,category,price,discount_percent,date
0,Flipkart,Samsung Galaxy S24 FE 5G,Mobile&Accessories,39999.0,33%,25-08-2025
1,Snapdeal,Samsung Galaxy S24 FE 5G,Mobile&Accessories,0.0,NaN,25-08-2025
2,Flipkart,Samsung S13 5G,Mobile&Accessories,267.0,73%,25-08-2025
3,Snapdeal,Samsung S13 5G,Mobile&Accessories,194.0,81%,25-08-2025
4,Flipkart,Men Casual Collar Shirt,MenFashion,311.0,79%,25-08-2025
5,Snapdeal,Men Casual Collar Shirt,MenFashion,293.0,71%,25-08-2025
6,Flipkart,Kanjivaram Silk Saree,WomenFashion,670.0,73%,25-08-2025
7,Snapdeal,Kanjivaram Silk Saree,WomenFashion,430.0,86%,25-08-2025
8,Flipkart,Cotton Straight Kurthi,WomenFashion,348.0,76%,25-08-2025
9,Snapdeal,Cotton Straight Kurthi,WomenFashion,297.0,58%,25-08-2025
10,Flipkart,TecSox Tecband Zap Bluetooth,Electronics,300.0,84%,25-08-2025
11,Snapdeal,TecSox Tecband Zap Bluetooth,Electronics,405.0,80%,25-08-2025
12,Flipkart,Sricom hum001 Portable Room Air Purifier,Home&Accessories,339.0,43%,25-08-2025
13,Snapdeal,KCS LITE Aroma diffuser humidifier,Home&Accessories,397.0,69%,25-08-2025
14,Flipkart,Baby boy regular cotton shirt,KidsFashion,203.0,79%,25-08-2025
15,Snapdeal,Baby boy regular cotton shirt,KidsFashion,166.0,67%,25-08-2025
16,Flipkart,Girl casual cotton frock,KidsFashion,249.0,89%,25-08-2025
17,Snapdeal,Girl casual cotton frock,KidsFashion,244.0,73%,25-08-2025
18,Flipkart,LG AI TV UR7500 108cm,Tvs&Appliances,31990.0,36%,25-08-2025
19,Snapdeal,NaN,Tvs&Appliances,0.0,NaN,25-08-2025
20,Flipkart,Atomic Habits,"Sports,Books&More",135.0,72%,25-08-2025
21,Snapdeal,Atomic Habits,Books,138.0,77%,25-08-2025
22,Flipkart,Carnest Car Body Cover,Automatives,1099.0,56%,25-08-2025
23,Snapdeal,Carnest Car Body Cover,"Sports,Books&More",505.0,68%,25-08-2025
24,Flipkart,Velox-740 Men Sport wear,"Sports,Books&More",400.0,86%,25-08-2025
25,Snapdeal,Campus HARRINUS Sport shoes,MenFootwear,807.0,53%,25-08-2025
26,Flipkart,Wow Aloevera Body Lotion,Beauty&SkinCare,264.0,41%,25-08-2025
27,Snapdeal,Wow Aloevera Body Lotion,Beauty&SkinCare,131.0,71%,25-08-2025
28,Flipkart,Mixed Nuts,FoodEssentials,526.0,59%,25-08-2025
29,Snapdeal,Mixed Nuts,DailyNeeds,581.0,42%,25-08-2025

In [17]:
df['company_name']=df['company_name'].astype('string')
df

,company_name,product_name,category,price,discount_percent,date
0,Flipkart,Samsung Galaxy S24 FE 5G,Mobile&Accessories,39999.0,33%,25-08-2025
1,Snapdeal,Samsung Galaxy S24 FE 5G,Mobile&Accessories,0.0,NaN,25-08-2025
2,Flipkart,Samsung S13 5G,Mobile&Accessories,267.0,73%,25-08-2025
3,Snapdeal,Samsung S13 5G,Mobile&Accessories,194.0,81%,25-08-2025
4,Flipkart,Men Casual Collar Shirt,MenFashion,311.0,79%,25-08-2025
5,Snapdeal,Men Casual Collar Shirt,MenFashion,293.0,71%,25-08-2025
6,Flipkart,Kanjivaram Silk Saree,WomenFashion,670.0,73%,25-08-2025
7,Snapdeal,Kanjivaram Silk Saree,WomenFashion,430.0,86%,25-08-2025
8,Flipkart,Cotton Straight Kurthi,WomenFashion,348.0,76%,25-08-2025
9,Snapdeal,Cotton Straight Kurthi,WomenFashion,297.0,58%,25-08-2025
10,Flipkart,TecSox Tecband Zap Bluetooth,Electronics,300.0,84%,25-08-2025
11,Snapdeal,TecSox Tecband Zap Bluetooth,Electronics,405.0,80%,25-08-2025
12,Flipkart,Sricom hum001 Portable Room Air Purifier,Home&Accessories,339.0,43%,25-08-2025
13,Snapdeal,KCS LITE Aroma diffuser humidifier,Home&Accessories,397.0,69%,25-08-2025
14,Flipkart,Baby boy regular cotton shirt,KidsFashion,203.0,79%,25-08-2025
15,Snapdeal,Baby boy regular cotton shirt,KidsFashion,166.0,67%,25-08-2025
16,Flipkart,Girl casual cotton frock,KidsFashion,249.0,89%,25-08-2025
17,Snapdeal,Girl casual cotton frock,KidsFashion,244.0,73%,25-08-2025
18,Flipkart,LG AI TV UR7500 108cm,Tvs&Appliances,31990.0,36%,25-08-2025
19,Snapdeal,NaN,Tvs&Appliances,0.0,NaN,25-08-2025
20,Flipkart,Atomic Habits,"Sports,Books&More",135.0,72%,25-08-2025
21,Snapdeal,Atomic Habits,Books,138.0,77%,25-08-2025
22,Flipkart,Carnest Car Body Cover,Automatives,1099.0,56%,25-08-2025
23,Snapdeal,Carnest Car Body Cover,"Sports,Books&More",505.0,68%,25-08-2025
24,Flipkart,Velox-740 Men Sport wear,"Sports,Books&More",400.0,86%,25-08-2025
25,Snapdeal,Campus HARRINUS Sport shoes,MenFootwear,807.0,53%,25-08-2025
26,Flipkart,Wow Aloevera Body Lotion,Beauty&SkinCare,264.0,41%,25-08-2025
27,Snapdeal,Wow Aloevera Body Lotion,Beauty&SkinCare,131.0,71%,25-08-2025
28,Flipkart,Mixed Nuts,FoodEssentials,526.0,59%,25-08-2025
29,Snapdeal,Mixed Nuts,DailyNeeds,581.0,42%,25-08-2025

In [21]:
df['discount_percent']=df['discount_percent'].astype('string').str.strip()
df['discount_percent']=df['discount_percent'].str.replace('%','')
df['discount_percent']=pd.to_numeric(df['discount_percent'],errors='coerce')
df['discount_percent']=df['discount_percent'].fillna(0)
print(df['discount_percent'].dtype)
df

Int64

,company_name,product_name,category,price,discount_percent,date
0,Flipkart,Samsung Galaxy S24 FE 5G,Mobile&Accessories,39999.0,33,25-08-2025
1,Snapdeal,Samsung Galaxy S24 FE 5G,Mobile&Accessories,0.0,0,25-08-2025
2,Flipkart,Samsung S13 5G,Mobile&Accessories,267.0,73,25-08-2025
3,Snapdeal,Samsung S13 5G,Mobile&Accessories,194.0,81,25-08-2025
4,Flipkart,Men Casual Collar Shirt,MenFashion,311.0,79,25-08-2025
5,Snapdeal,Men Casual Collar Shirt,MenFashion,293.0,71,25-08-2025
6,Flipkart,Kanjivaram Silk Saree,WomenFashion,670.0,73,25-08-2025
7,Snapdeal,Kanjivaram Silk Saree,WomenFashion,430.0,86,25-08-2025
8,Flipkart,Cotton Straight Kurthi,WomenFashion,348.0,76,25-08-2025
9,Snapdeal,Cotton Straight Kurthi,WomenFashion,297.0,58,25-08-2025
10,Flipkart,TecSox Tecband Zap Bluetooth,Electronics,300.0,84,25-08-2025
11,Snapdeal,TecSox Tecband Zap Bluetooth,Electronics,405.0,80,25-08-2025
12,Flipkart,Sricom hum001 Portable Room Air Purifier,Home&Accessories,339.0,43,25-08-2025
13,Snapdeal,KCS LITE Aroma diffuser humidifier,Home&Accessories,397.0,69,25-08-2025
14,Flipkart,Baby boy regular cotton shirt,KidsFashion,203.0,79,25-08-2025
15,Snapdeal,Baby boy regular cotton shirt,KidsFashion,166.0,67,25-08-2025
16,Flipkart,Girl casual cotton frock,KidsFashion,249.0,89,25-08-2025
17,Snapdeal,Girl casual cotton frock,KidsFashion,244.0,73,25-08-2025
18,Flipkart,LG AI TV UR7500 108cm,Tvs&Appliances,31990.0,36,25-08-2025
19,Snapdeal,NaN,Tvs&Appliances,0.0,0,25-08-2025
20,Flipkart,Atomic Habits,"Sports,Books&More",135.0,72,25-08-2025
21,Snapdeal,Atomic Habits,Books,138.0,77,25-08-2025
22,Flipkart,Carnest Car Body Cover,Automatives,1099.0,56,25-08-2025
23,Snapdeal,Carnest Car Body Cover,"Sports,Books&More",505.0,68,25-08-2025
24,Flipkart,Velox-740 Men Sport wear,"Sports,Books&More",400.0,86,25-08-2025
25,Snapdeal,Campus HARRINUS Sport shoes,MenFootwear,807.0,53,25-08-2025
26,Flipkart,Wow Aloevera Body Lotion,Beauty&SkinCare,264.0,41,25-08-2025
27,Snapdeal,Wow Aloevera Body Lotion,Beauty&SkinCare,131.0,71,25-08-2025
28,Flipkart,Mixed Nuts,FoodEssentials,526.0,59,25-08-2025
29,Snapdeal,Mixed Nuts,DailyNeeds,581.0,42,25-08-2025

In [22]:
df.dtypes

company_name        string[python]
product_name                object
category                    object
price                      float64
discount_percent             Int64
date                        object
dtype: object

In [25]:
df=df.astype({'product_name':'string','category':'string','date':'datetime64[s]'})
print(df.dtypes)

company_name        string[python]
product_name        string[python]
category            string[python]
price                      float64
discount_percent             Int64
date                 datetime64[s]
dtype: object

In [28]:
df['company_name']=df['company_name'].str.rstrip()
df['company_name']=df['company_name'].str.lstrip()
df

,company_name,product_name,category,price,discount_percent,date
0,Flipkart,Samsung Galaxy S24 FE 5G,Mobile&Accessories,39999.0,33,2025-08-25
1,Snapdeal,Samsung Galaxy S24 FE 5G,Mobile&Accessories,0.0,0,2025-08-25
2,Flipkart,Samsung S13 5G,Mobile&Accessories,267.0,73,2025-08-25
3,Snapdeal,Samsung S13 5G,Mobile&Accessories,194.0,81,2025-08-25
4,Flipkart,Men Casual Collar Shirt,MenFashion,311.0,79,2025-08-25
5,Snapdeal,Men Casual Collar Shirt,MenFashion,293.0,71,2025-08-25
6,Flipkart,Kanjivaram Silk Saree,WomenFashion,670.0,73,2025-08-25
7,Snapdeal,Kanjivaram Silk Saree,WomenFashion,430.0,86,2025-08-25
8,Flipkart,Cotton Straight Kurthi,WomenFashion,348.0,76,2025-08-25
9,Snapdeal,Cotton Straight Kurthi,WomenFashion,297.0,58,2025-08-25
10,Flipkart,TecSox Tecband Zap Bluetooth,Electronics,300.0,84,2025-08-25
11,Snapdeal,TecSox Tecband Zap Bluetooth,Electronics,405.0,80,2025-08-25
12,Flipkart,Sricom hum001 Portable Room Air Purifier,Home&Accessories,339.0,43,2025-08-25
13,Snapdeal,KCS LITE Aroma diffuser humidifier,Home&Accessories,397.0,69,2025-08-25
14,Flipkart,Baby boy regular cotton shirt,KidsFashion,203.0,79,2025-08-25
15,Snapdeal,Baby boy regular cotton shirt,KidsFashion,166.0,67,2025-08-25
16,Flipkart,Girl casual cotton frock,KidsFashion,249.0,89,2025-08-25
17,Snapdeal,Girl casual cotton frock,KidsFashion,244.0,73,2025-08-25
18,Flipkart,LG AI TV UR7500 108cm,Tvs&Appliances,31990.0,36,2025-08-25
19,Snapdeal,<NA>,Tvs&Appliances,0.0,0,2025-08-25
20,Flipkart,Atomic Habits,"Sports,Books&More",135.0,72,2025-08-25
21,Snapdeal,Atomic Habits,Books,138.0,77,2025-08-25
22,Flipkart,Carnest Car Body Cover,Automatives,1099.0,56,2025-08-25
23,Snapdeal,Carnest Car Body Cover,"Sports,Books&More",505.0,68,2025-08-25
24,Flipkart,Velox-740 Men Sport wear,"Sports,Books&More",400.0,86,2025-08-25
25,Snapdeal,Campus HARRINUS Sport shoes,MenFootwear,807.0,53,2025-08-25
26,Flipkart,Wow Aloevera Body Lotion,Beauty&SkinCare,264.0,41,2025-08-25
27,Snapdeal,Wow Aloevera Body Lotion,Beauty&SkinCare,131.0,71,2025-08-25
28,Flipkart,Mixed Nuts,FoodEssentials,526.0,59,2025-08-25
29,Snapdeal,Mixed Nuts,DailyNeeds,581.0,42,2025-08-25

In [33]:
df['product_name']=df['product_name'].fillna('')
df['product_name']=df['product_name'].str.rstrip()
df['product_name']=df['product_name'].str.lstrip()
df

,company_name,product_name,category,price,discount_percent,date
0,Flipkart,Samsung Galaxy S24 FE 5G,Mobile&Accessories,39999.0,33,2025-08-25
1,Snapdeal,Samsung Galaxy S24 FE 5G,Mobile&Accessories,0.0,0,2025-08-25
2,Flipkart,Samsung S13 5G,Mobile&Accessories,267.0,73,2025-08-25
3,Snapdeal,Samsung S13 5G,Mobile&Accessories,194.0,81,2025-08-25
4,Flipkart,Men Casual Collar Shirt,MenFashion,311.0,79,2025-08-25
5,Snapdeal,Men Casual Collar Shirt,MenFashion,293.0,71,2025-08-25
6,Flipkart,Kanjivaram Silk Saree,WomenFashion,670.0,73,2025-08-25
7,Snapdeal,Kanjivaram Silk Saree,WomenFashion,430.0,86,2025-08-25
8,Flipkart,Cotton Straight Kurthi,WomenFashion,348.0,76,2025-08-25
9,Snapdeal,Cotton Straight Kurthi,WomenFashion,297.0,58,2025-08-25
10,Flipkart,TecSox Tecband Zap Bluetooth,Electronics,300.0,84,2025-08-25
11,Snapdeal,TecSox Tecband Zap Bluetooth,Electronics,405.0,80,2025-08-25
12,Flipkart,Sricom hum001 Portable Room Air Purifier,Home&Accessories,339.0,43,2025-08-25
13,Snapdeal,KCS LITE Aroma diffuser humidifier,Home&Accessories,397.0,69,2025-08-25
14,Flipkart,Baby boy regular cotton shirt,KidsFashion,203.0,79,2025-08-25
15,Snapdeal,Baby boy regular cotton shirt,KidsFashion,166.0,67,2025-08-25
16,Flipkart,Girl casual cotton frock,KidsFashion,249.0,89,2025-08-25
17,Snapdeal,Girl casual cotton frock,KidsFashion,244.0,73,2025-08-25
18,Flipkart,LG AI TV UR7500 108cm,Tvs&Appliances,31990.0,36,2025-08-25
19,Snapdeal,,Tvs&Appliances,0.0,0,2025-08-25
20,Flipkart,Atomic Habits,"Sports,Books&More",135.0,72,2025-08-25
21,Snapdeal,Atomic Habits,Books,138.0,77,2025-08-25
22,Flipkart,Carnest Car Body Cover,Automatives,1099.0,56,2025-08-25
23,Snapdeal,Carnest Car Body Cover,"Sports,Books&More",505.0,68,2025-08-25
24,Flipkart,Velox-740 Men Sport wear,"Sports,Books&More",400.0,86,2025-08-25
25,Snapdeal,Campus HARRINUS Sport shoes,MenFootwear,807.0,53,2025-08-25
26,Flipkart,Wow Aloevera Body Lotion,Beauty&SkinCare,264.0,41,2025-08-25
27,Snapdeal,Wow Aloevera Body Lotion,Beauty&SkinCare,131.0,71,2025-08-25
28,Flipkart,Mixed Nuts,FoodEssentials,526.0,59,2025-08-25
29,Snapdeal,Mixed Nuts,DailyNeeds,581.0,42,2025-08-25

In [35]:
df.to_csv('flipkartpricing.csv',index=False)

In [2]:
import pandas as pd
df=pd.read_csv('Funding.csv')
df

,Company_name,Funding_round,Date,Amount_usd,Investor,No Of Investors
0,Flipkart,Series A - Flipkart,01-10-2009,$1.00 Mn,"Accel, Tiger Global Management",2
1,Flipkart,Series B - Flipkart,16-06-2010,$10.00 Mn,Tiger Global Management,1
2,Flipkart,Series C - Flipkart,16-06-2011,$20.00 Mn,"KG Investment, Tiger Global Management",2
3,Flipkart,Series D - Flipkart,24-08-2012,$150.00 Mn,"Accel,ICONIQ Capital,Naspers,Tiger Global Mana...",4
4,Flipkart,Series E - Flipkart,10-07-2013,$200.00 Mn,"Accel,ICONIQ Capital,Naspers,Tiger Global Mana...",4
5,Flipkart,Series E - Flipkart,08-10-2013,$160.00 Mn,"Dragoneer Investment Group,Morgan Stanely, sof...",6
6,Flipkart,Series F - Flipkart,26-05-2014,$210.00 Mn,"DST Global,Tiger Global Management, ICONIQ Gro...",4
7,Flipkart,Series G - Flipkart,29-07-2014,$1.00 Bn,"Accel, Margan Stanely,Sofina,Vulcan Capital,GI...",9
8,Flipkart,Series H - Flipkart,21-12-2014,$700.00 Mn,"Baillie Gifford,Qatar Investment Authority,GIC...",9
9,Flipkart,Series I - Flipkart,04-06-2015,$50.00 Mn,Morgan Stanely,1
10,Flipkart,Private Equity- Flipkart,28-07-2015,$700.00 Mn,"ICONIQ Growth,Steadview Capital,Tiger Global M...",3
11,Flipkart,Dept Funding- Flipkart,07-05-2016,$67.00 Mn,HDFC Bank,1
12,Flipkart,Seies J-Flipkart,10-04-2017,$1.00 Bn,"eBay,Microsoft,Tencent",3
13,Flipkart,Private Equity- Flipkart,26-06-2017,$71.00 Mn,Naspers,1
14,Flipkart,Private Equity- Flipkart,10-08-2017,$2.50 Bn,SoftBank Vision Found,1
15,Flipkart,Corporate Round-Flipkart,25-10-2017,Undisclosed,"eBay,Microsoft,Tencent",1
16,Flipkart,Secondary Market-Flipkart,04-09-2019,$14.50 Mn,Tiger Global Management,1
17,Flipkart,Corporate Round-Flipkart,10-09-2019,$224.85Mn,Flipkart,1
18,Flipkart,Corporate Round-Flipkart,14-07-2020,$1.20Bn,Walmart,1
19,Flipkart,Corporate Round-Flipkart,16-09-2020,$62.80Mn,Tencent,1
20,Flipkart,Private Equity- Flipkart,12-07-2021,$3.60Bn,"Antara Capital Master Fund,CPP Investments,Dis...",12
21,Flipkart,Secondary Market-Flipkart,13-06-2022,$264.00Mn,Tencent,1
22,Flipkart,Secondary Market-Flipkart,13-07-2023,$1.40Bn,Walmart,1
23,Snapdeal,Series A-Snapdeal,01-01-2009,Undisclosed,Kalaari Capital,1
24,Snapdeal,Series A-Snapdeal,25-01-2011,$12.00Mn,"Kalaari Capital,Nexus Venture Partners",2
25,Snapdeal,Series B-Snapdeal,01-07-2011,$40.00Mn,"Kalaari Capital,Nexus Venture Partners,Besseme...",3
26,Snapdeal,Series C-Snapdeal,01-04-2013,$50.00Mn,"Bessemer Venture Parters,Cambrian Ventures, eB...",9
27,Snapdeal,Undisclosed-Snapdeal,13-08-2013,$75.00Mn,SoftBank Capital,1
28,Snapdeal,Series D-Snapdeal,26-02-2014,$134.00Mn,"Bessemer Venture Parters,eBay,Intel Capital,Ka...",6
29,Snapdeal,Series E-Snapdeal,20-05-2014,$100.00Mn,"BlackRock,Myriad Group,PremjiInvest,TemasekHol...",5
30,Snapdeal,Undisclosed-Snapdeal,27-08-2014,Undisclosed,Ratan TaTa,1
31,Snapdeal,Undisclosed-Snapdeal,27-10-2014,$627.00Mn,SoftBank Telecom corp,1
32,Snapdeal,Series G-Snapdeal,01-08-2015,$500.00Mn,"Alibaba Group,Bank Capital,Foxconn Technology ...",3
33,Snapdeal,Secondary Market-Flipkart,14-02-2016,$200.00Mn,"Iron Pillar,Ontaria,Teachers Pension Plansodium",2
34,Snapdeal,Undisclosed-Snapdeal,26-08-2016,$21.00Mn,Clouse SA,1
35,Snapdeal,Undisclosed-Snapdeal,29-05-2017,$17.56Mn,"Kunal Bahil,Nexus Venture Parters, Rohith Bansel",3
36,Snapdeal,Undisclosed-Snapdeal,23-07-2019,Undisclosed,Anand Piramal,1

In [46]:

df.columns=df.columns.str.strip()
print(list(df.columns))

['Company_name', 'Funding_round', 'Date', 'Amount_usd', 'Investor', 'No Of Investors']

In [49]:
df['Company_name']=df['Company_name'].astype('string')
df['Company_name']=df['Company_name'].str.strip()
print(df['Company_name'].dtype)
df

string

,Company_name,Funding_round,Date,Amount_usd,Investor,No Of Investors
0,Flipkart,Series A - Flipkart,01-10-2009,$1.00 Mn,"Accel, Tiger Global Management",2
1,Flipkart,Series B - Flipkart,16-06-2010,$10.00 Mn,Tiger Global Management,1
2,Flipkart,Series C - Flipkart,16-06-2011,$20.00 Mn,"KG Investment, Tiger Global Management",2
3,Flipkart,Series D - Flipkart,24-08-2012,$150.00 Mn,"Accel,ICONIQ Capital,Naspers,Tiger Global Mana...",4
4,Flipkart,Series E - Flipkart,10-07-2013,$200.00 Mn,"Accel,ICONIQ Capital,Naspers,Tiger Global Mana...",4
5,Flipkart,Series E - Flipkart,08-10-2013,$160.00 Mn,"Dragoneer Investment Group,Morgan Stanely, sof...",6
6,Flipkart,Series F - Flipkart,26-05-2014,$210.00 Mn,"DST Global,Tiger Global Management, ICONIQ Gro...",4
7,Flipkart,Series G - Flipkart,29-07-2014,$1.00 Bn,"Accel, Margan Stanely,Sofina,Vulcan Capital,GI...",9
8,Flipkart,Series H - Flipkart,21-12-2014,$700.00 Mn,"Baillie Gifford,Qatar Investment Authority,GIC...",9
9,Flipkart,Series I - Flipkart,04-06-2015,$50.00 Mn,Morgan Stanely,1
10,Flipkart,Private Equity- Flipkart,28-07-2015,$700.00 Mn,"ICONIQ Growth,Steadview Capital,Tiger Global M...",3
11,Flipkart,Dept Funding- Flipkart,07-05-2016,$67.00 Mn,HDFC Bank,1
12,Flipkart,Seies J-Flipkart,10-04-2017,$1.00 Bn,"eBay,Microsoft,Tencent",3
13,Flipkart,Private Equity- Flipkart,26-06-2017,$71.00 Mn,Naspers,1
14,Flipkart,Private Equity- Flipkart,10-08-2017,$2.50 Bn,SoftBank Vision Found,1
15,Flipkart,Corporate Round-Flipkart,25-10-2017,Undisclosed,"eBay,Microsoft,Tencent",1
16,Flipkart,Secondary Market-Flipkart,04-09-2019,$14.50 Mn,Tiger Global Management,1
17,Flipkart,Corporate Round-Flipkart,10-09-2019,$224.85Mn,Flipkart,1
18,Flipkart,Corporate Round-Flipkart,14-07-2020,$1.20Bn,Walmart,1
19,Flipkart,Corporate Round-Flipkart,16-09-2020,$62.80Mn,Tencent,1
20,Flipkart,Private Equity- Flipkart,12-07-2021,$3.60Bn,"Antara Capital Master Fund,CPP Investments,Dis...",12
21,Flipkart,Secondary Market-Flipkart,13-06-2022,$264.00Mn,Tencent,1
22,Flipkart,Secondary Market-Flipkart,13-07-2023,$1.40Bn,Walmart,1
23,Snapdeal,Series A-Snapdeal,01-01-2009,Undisclosed,Kalaari Capital,1
24,Snapdeal,Series A-Snapdeal,25-01-2011,$12.00Mn,"Kalaari Capital,Nexus Venture Partners",2
25,Snapdeal,Series B-Snapdeal,01-07-2011,$40.00Mn,"Kalaari Capital,Nexus Venture Partners,Besseme...",3
26,Snapdeal,Series C-Snapdeal,01-04-2013,$50.00Mn,"Bessemer Venture Parters,Cambrian Ventures, eB...",9
27,Snapdeal,Undisclosed-Snapdeal,13-08-2013,$75.00Mn,SoftBank Capital,1
28,Snapdeal,Series D-Snapdeal,26-02-2014,$134.00Mn,"Bessemer Venture Parters,eBay,Intel Capital,Ka...",6
29,Snapdeal,Series E-Snapdeal,20-05-2014,$100.00Mn,"BlackRock,Myriad Group,PremjiInvest,TemasekHol...",5
30,Snapdeal,Undisclosed-Snapdeal,27-08-2014,Undisclosed,Ratan TaTa,1
31,Snapdeal,Undisclosed-Snapdeal,27-10-2014,$627.00Mn,SoftBank Telecom corp,1
32,Snapdeal,Series G-Snapdeal,01-08-2015,$500.00Mn,"Alibaba Group,Bank Capital,Foxconn Technology ...",3
33,Snapdeal,Secondary Market-Flipkart,14-02-2016,$200.00Mn,"Iron Pillar,Ontaria,Teachers Pension Plansodium",2
34,Snapdeal,Undisclosed-Snapdeal,26-08-2016,$21.00Mn,Clouse SA,1
35,Snapdeal,Undisclosed-Snapdeal,29-05-2017,$17.56Mn,"Kunal Bahil,Nexus Venture Parters, Rohith Bansel",3
36,Snapdeal,Undisclosed-Snapdeal,23-07-2019,Undisclosed,Anand Piramal,1

In [55]:
df=df.astype({'Funding_round':'string','Date':'string'})
col_striping=['Funding_round','Date']
df[col_striping]=df[col_striping].apply(lambda x:x.str.strip())
df['Date']=df['Date'].astype('datetime64[s]')
print(df.dtypes)
df

Company_name       string[python]
Funding_round      string[python]
Date                datetime64[s]
Amount_usd                 object
Investor                   object
No Of Investors             int64
dtype: object

,Company_name,Funding_round,Date,Amount_usd,Investor,No Of Investors
0,Flipkart,Series A - Flipkart,2009-01-10,$1.00 Mn,"Accel, Tiger Global Management",2
1,Flipkart,Series B - Flipkart,2010-06-16,$10.00 Mn,Tiger Global Management,1
2,Flipkart,Series C - Flipkart,2011-06-16,$20.00 Mn,"KG Investment, Tiger Global Management",2
3,Flipkart,Series D - Flipkart,2012-08-24,$150.00 Mn,"Accel,ICONIQ Capital,Naspers,Tiger Global Mana...",4
4,Flipkart,Series E - Flipkart,2013-10-07,$200.00 Mn,"Accel,ICONIQ Capital,Naspers,Tiger Global Mana...",4
5,Flipkart,Series E - Flipkart,2013-08-10,$160.00 Mn,"Dragoneer Investment Group,Morgan Stanely, sof...",6
6,Flipkart,Series F - Flipkart,2014-05-26,$210.00 Mn,"DST Global,Tiger Global Management, ICONIQ Gro...",4
7,Flipkart,Series G - Flipkart,2014-07-29,$1.00 Bn,"Accel, Margan Stanely,Sofina,Vulcan Capital,GI...",9
8,Flipkart,Series H - Flipkart,2014-12-21,$700.00 Mn,"Baillie Gifford,Qatar Investment Authority,GIC...",9
9,Flipkart,Series I - Flipkart,2015-04-06,$50.00 Mn,Morgan Stanely,1
10,Flipkart,Private Equity- Flipkart,2015-07-28,$700.00 Mn,"ICONIQ Growth,Steadview Capital,Tiger Global M...",3
11,Flipkart,Dept Funding- Flipkart,2016-07-05,$67.00 Mn,HDFC Bank,1
12,Flipkart,Seies J-Flipkart,2017-10-04,$1.00 Bn,"eBay,Microsoft,Tencent",3
13,Flipkart,Private Equity- Flipkart,2017-06-26,$71.00 Mn,Naspers,1
14,Flipkart,Private Equity- Flipkart,2017-10-08,$2.50 Bn,SoftBank Vision Found,1
15,Flipkart,Corporate Round-Flipkart,2017-10-25,Undisclosed,"eBay,Microsoft,Tencent",1
16,Flipkart,Secondary Market-Flipkart,2019-04-09,$14.50 Mn,Tiger Global Management,1
17,Flipkart,Corporate Round-Flipkart,2019-10-09,$224.85Mn,Flipkart,1
18,Flipkart,Corporate Round-Flipkart,2020-07-14,$1.20Bn,Walmart,1
19,Flipkart,Corporate Round-Flipkart,2020-09-16,$62.80Mn,Tencent,1
20,Flipkart,Private Equity- Flipkart,2021-12-07,$3.60Bn,"Antara Capital Master Fund,CPP Investments,Dis...",12
21,Flipkart,Secondary Market-Flipkart,2022-06-13,$264.00Mn,Tencent,1
22,Flipkart,Secondary Market-Flipkart,2023-07-13,$1.40Bn,Walmart,1
23,Snapdeal,Series A-Snapdeal,2009-01-01,Undisclosed,Kalaari Capital,1
24,Snapdeal,Series A-Snapdeal,2011-01-25,$12.00Mn,"Kalaari Capital,Nexus Venture Partners",2
25,Snapdeal,Series B-Snapdeal,2011-01-07,$40.00Mn,"Kalaari Capital,Nexus Venture Partners,Besseme...",3
26,Snapdeal,Series C-Snapdeal,2013-01-04,$50.00Mn,"Bessemer Venture Parters,Cambrian Ventures, eB...",9
27,Snapdeal,Undisclosed-Snapdeal,2013-08-13,$75.00Mn,SoftBank Capital,1
28,Snapdeal,Series D-Snapdeal,2014-02-26,$134.00Mn,"Bessemer Venture Parters,eBay,Intel Capital,Ka...",6
29,Snapdeal,Series E-Snapdeal,2014-05-20,$100.00Mn,"BlackRock,Myriad Group,PremjiInvest,TemasekHol...",5
30,Snapdeal,Undisclosed-Snapdeal,2014-08-27,Undisclosed,Ratan TaTa,1
31,Snapdeal,Undisclosed-Snapdeal,2014-10-27,$627.00Mn,SoftBank Telecom corp,1
32,Snapdeal,Series G-Snapdeal,2015-01-08,$500.00Mn,"Alibaba Group,Bank Capital,Foxconn Technology ...",3
33,Snapdeal,Secondary Market-Flipkart,2016-02-14,$200.00Mn,"Iron Pillar,Ontaria,Teachers Pension Plansodium",2
34,Snapdeal,Undisclosed-Snapdeal,2016-08-26,$21.00Mn,Clouse SA,1
35,Snapdeal,Undisclosed-Snapdeal,2017-05-29,$17.56Mn,"Kunal Bahil,Nexus Venture Parters, Rohith Bansel",3
36,Snapdeal,Undisclosed-Snapdeal,2019-07-23,Undisclosed,Anand Piramal,1

In [12]:
df['Amount_usd']=df['Amount_usd'].astype('string').str.replace('$','').str.replace('Mn','').str.replace('Bn','')
df['Amount_usd']=pd.to_numeric(df['Amount_usd'],errors='coerce')
df['Amount_usd']=df['Amount_usd'].fillna(0)
df['Investor']=df['Investor'].astype('string').str.strip()
print(df.dtypes)
df

Company_name               object
Funding_round              object
Date                       object
Amount_usd                Float64
Investor           string[python]
No Of Investors             int64
dtype: object

,Company_name,Funding_round,Date,Amount_usd,Investor,No Of Investors
0,Flipkart,Series A - Flipkart,01-10-2009,1.0,"Accel, Tiger Global Management",2
1,Flipkart,Series B - Flipkart,16-06-2010,10.0,Tiger Global Management,1
2,Flipkart,Series C - Flipkart,16-06-2011,20.0,"KG Investment, Tiger Global Management",2
3,Flipkart,Series D - Flipkart,24-08-2012,150.0,"Accel,ICONIQ Capital,Naspers,Tiger Global Mana...",4
4,Flipkart,Series E - Flipkart,10-07-2013,200.0,"Accel,ICONIQ Capital,Naspers,Tiger Global Mana...",4
5,Flipkart,Series E - Flipkart,08-10-2013,160.0,"Dragoneer Investment Group,Morgan Stanely, sof...",6
6,Flipkart,Series F - Flipkart,26-05-2014,210.0,"DST Global,Tiger Global Management, ICONIQ Gro...",4
7,Flipkart,Series G - Flipkart,29-07-2014,1.0,"Accel, Margan Stanely,Sofina,Vulcan Capital,GI...",9
8,Flipkart,Series H - Flipkart,21-12-2014,700.0,"Baillie Gifford,Qatar Investment Authority,GIC...",9
9,Flipkart,Series I - Flipkart,04-06-2015,50.0,Morgan Stanely,1
10,Flipkart,Private Equity- Flipkart,28-07-2015,700.0,"ICONIQ Growth,Steadview Capital,Tiger Global M...",3
11,Flipkart,Dept Funding- Flipkart,07-05-2016,67.0,HDFC Bank,1
12,Flipkart,Seies J-Flipkart,10-04-2017,1.0,"eBay,Microsoft,Tencent",3
13,Flipkart,Private Equity- Flipkart,26-06-2017,71.0,Naspers,1
14,Flipkart,Private Equity- Flipkart,10-08-2017,2.5,SoftBank Vision Found,1
15,Flipkart,Corporate Round-Flipkart,25-10-2017,0.0,"eBay,Microsoft,Tencent",1
16,Flipkart,Secondary Market-Flipkart,04-09-2019,14.5,Tiger Global Management,1
17,Flipkart,Corporate Round-Flipkart,10-09-2019,224.85,Flipkart,1
18,Flipkart,Corporate Round-Flipkart,14-07-2020,1.2,Walmart,1
19,Flipkart,Corporate Round-Flipkart,16-09-2020,62.8,Tencent,1
20,Flipkart,Private Equity- Flipkart,12-07-2021,3.6,"Antara Capital Master Fund,CPP Investments,Dis...",12
21,Flipkart,Secondary Market-Flipkart,13-06-2022,264.0,Tencent,1
22,Flipkart,Secondary Market-Flipkart,13-07-2023,1.4,Walmart,1
23,Snapdeal,Series A-Snapdeal,01-01-2009,0.0,Kalaari Capital,1
24,Snapdeal,Series A-Snapdeal,25-01-2011,12.0,"Kalaari Capital,Nexus Venture Partners",2
25,Snapdeal,Series B-Snapdeal,01-07-2011,40.0,"Kalaari Capital,Nexus Venture Partners,Besseme...",3
26,Snapdeal,Series C-Snapdeal,01-04-2013,50.0,"Bessemer Venture Parters,Cambrian Ventures, eB...",9
27,Snapdeal,Undisclosed-Snapdeal,13-08-2013,75.0,SoftBank Capital,1
28,Snapdeal,Series D-Snapdeal,26-02-2014,134.0,"Bessemer Venture Parters,eBay,Intel Capital,Ka...",6
29,Snapdeal,Series E-Snapdeal,20-05-2014,100.0,"BlackRock,Myriad Group,PremjiInvest,TemasekHol...",5
30,Snapdeal,Undisclosed-Snapdeal,27-08-2014,0.0,Ratan TaTa,1
31,Snapdeal,Undisclosed-Snapdeal,27-10-2014,627.0,SoftBank Telecom corp,1
32,Snapdeal,Series G-Snapdeal,01-08-2015,500.0,"Alibaba Group,Bank Capital,Foxconn Technology ...",3
33,Snapdeal,Secondary Market-Flipkart,14-02-2016,200.0,"Iron Pillar,Ontaria,Teachers Pension Plansodium",2
34,Snapdeal,Undisclosed-Snapdeal,26-08-2016,21.0,Clouse SA,1
35,Snapdeal,Undisclosed-Snapdeal,29-05-2017,17.56,"Kunal Bahil,Nexus Venture Parters, Rohith Bansel",3
36,Snapdeal,Undisclosed-Snapdeal,23-07-2019,0.0,Anand Piramal,1

In [15]:
df.to_csv('fundlist.csv',index=False)

In [16]:
df=pd.read_csv('Market_share.csv')
df

   Company_name  Year Market_share_per   Company Market_share_per.1
0      Flipkart  2012              35%  Snapdeal                 7%
1      Flipkart  2013              44%  Snapdeal                15%
2      Flipkart  2014              44%  Snapdeal                32%
3      Flipkart  2015              45%  Snapdeal                26%
4      Flipkart  2016              37%  Snapdeal                19%
5      Flipkart  2017              35%  Snapdeal                 4%
6      Flipkart  2018              38%  Snapdeal                 3%
7      Flipkart  2019              44%  Snapdeal                 4%
8      Flipkart  2020              44%  Snapdeal                 6%
9      Flipkart  2021              48%  Snapdeal                13%
10     Flipkart  2022              38%  Snapdeal                13%
11     Flipkart  2023              48%  Snapdeal                13%
12     Flipkart  2024              48%  Snapdeal                13%

In [23]:
df=df.rename(columns=({'Company_name':'company1','Company':'company2','Market_share_per':'Market_share_per1','Market_share_per.1':'Market_share_per2'}))
df

    company1  Year Market_share_per1  company2 Market_share_per2
0   Flipkart  2012               35%  Snapdeal                7%
1   Flipkart  2013               44%  Snapdeal               15%
2   Flipkart  2014               44%  Snapdeal               32%
3   Flipkart  2015               45%  Snapdeal               26%
4   Flipkart  2016               37%  Snapdeal               19%
5   Flipkart  2017               35%  Snapdeal                4%
6   Flipkart  2018               38%  Snapdeal                3%
7   Flipkart  2019               44%  Snapdeal                4%
8   Flipkart  2020               44%  Snapdeal                6%
9   Flipkart  2021               48%  Snapdeal               13%
10  Flipkart  2022               38%  Snapdeal               13%
11  Flipkart  2023               48%  Snapdeal               13%
12  Flipkart  2024               48%  Snapdeal               13%

In [28]:
df=df.astype({'company1':'string','Market_share_per1':'string','company2':'string','Market_share_per2':'string'})
df['Market_share_per1']=df['Market_share_per1'].str.replace('%','').str.strip()
df['Market_share_per1']=pd.to_numeric(df['Market_share_per1'],errors='coerce')
df['Market_share_per2']=df['Market_share_per2'].str.replace('%','').str.strip()
df['Market_share_per2']=pd.to_numeric(df['Market_share_per2'],errors='coerce')
print(df.dtypes)
df

company1             string[python]
Year                          int64
Market_share_per1             Int64
company2             string[python]
Market_share_per2             Int64
dtype: object

    company1  Year  Market_share_per1  company2  Market_share_per2
0   Flipkart  2012                 35  Snapdeal                  7
1   Flipkart  2013                 44  Snapdeal                 15
2   Flipkart  2014                 44  Snapdeal                 32
3   Flipkart  2015                 45  Snapdeal                 26
4   Flipkart  2016                 37  Snapdeal                 19
5   Flipkart  2017                 35  Snapdeal                  4
6   Flipkart  2018                 38  Snapdeal                  3
7   Flipkart  2019                 44  Snapdeal                  4
8   Flipkart  2020                 44  Snapdeal                  6
9   Flipkart  2021                 48  Snapdeal                 13
10  Flipkart  2022                 38  Snapdeal                 13
11  Flipkart  2023                 48  Snapdeal                 13
12  Flipkart  2024                 48  Snapdeal                 13

In [29]:
df.to_csv('Market_share.csv',index=False)

In [41]:
df=pd.read_csv('Social_media.csv')
df

  Company_name   Platform Follewers Engagement_rate        Date
0     Flipkart  Instagram        8M           1.50%  23-08-2025
1     Flipkart    Youtube      1.2M           3.07%  24-08-2025
2     Flipkart    Twitter        2M           0.60%  25-08-2025
3     Flipkart   Facebook       11M           0.80%  26-08-2025
4     Snapdeal  Instagram        1M           0.90%  27-08-2025
5     Snapdeal    Youtube     0.91M           0.14%  28-08-2025
6     Snapdeal    Twitter      0.2M           0.40%  29-08-2025
7     Snapdeal   Facebook      6.7M           0.50%  30-08-2025

In [42]:
df=df.apply(lambda c:c.str.strip() if c.dtype=='object' else c)
df=df.rename(columns=({'Follewers':'Followers'}))

In [43]:
df=df.astype({'Company_name':'string','Platform':'string','Followers':'string','Engagement_rate':'string','Date':'datetime64[s]'})
print(df.dtypes)
df

Company_name       string[python]
Platform           string[python]
Followers          string[python]
Engagement_rate    string[python]
Date                datetime64[s]
dtype: object

  Company_name   Platform Followers Engagement_rate       Date
0     Flipkart  Instagram        8M           1.50% 2025-08-23
1     Flipkart    Youtube      1.2M           3.07% 2025-08-24
2     Flipkart    Twitter        2M           0.60% 2025-08-25
3     Flipkart   Facebook       11M           0.80% 2025-08-26
4     Snapdeal  Instagram        1M           0.90% 2025-08-27
5     Snapdeal    Youtube     0.91M           0.14% 2025-08-28
6     Snapdeal    Twitter      0.2M           0.40% 2025-08-29
7     Snapdeal   Facebook      6.7M           0.50% 2025-08-30

In [ ]:
df['Followers']=df['Followers'].str.replace('M','')
df['Followers']=pd.to_numeric(df['Followers'],errors='coerce')
df

  Company_name   Platform  Followers Engagement_rate       Date
0     Flipkart  Instagram        8.0           1.50% 2025-08-23
1     Flipkart    Youtube        1.2           3.07% 2025-08-24
2     Flipkart    Twitter        2.0           0.60% 2025-08-25
3     Flipkart   Facebook       11.0           0.80% 2025-08-26
4     Snapdeal  Instagram        1.0           0.90% 2025-08-27
5     Snapdeal    Youtube       0.91           0.14% 2025-08-28
6     Snapdeal    Twitter        0.2           0.40% 2025-08-29
7     Snapdeal   Facebook        6.7           0.50% 2025-08-30

In [49]:
df['Engagement_rate']=df['Engagement_rate'].str.replace('%','')
df['Engagement_rate']=pd.to_numeric(df['Engagement_rate'],errors='coerce')
df

  Company_name   Platform  Followers  Engagement_rate       Date
0     Flipkart  Instagram        8.0              1.5 2025-08-23
1     Flipkart    Youtube        1.2             3.07 2025-08-24
2     Flipkart    Twitter        2.0              0.6 2025-08-25
3     Flipkart   Facebook       11.0              0.8 2025-08-26
4     Snapdeal  Instagram        1.0              0.9 2025-08-27
5     Snapdeal    Youtube       0.91             0.14 2025-08-28
6     Snapdeal    Twitter        0.2              0.4 2025-08-29
7     Snapdeal   Facebook        6.7              0.5 2025-08-30

In [50]:
df.to_csv('Social_media.csv',index=False)

In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('website_traffic.csv')
df

,Year,Flipkart_Visits_Million,Snapdeal_Visits_Million,Flipkart_Bounce_Rate_%,Snapdeal_Bounce_Rate_%,Flipkart_Avg_Session_Min,Snapdeal_Avg_Session_Min,Flipkart_Pages_Per_Visit,Snapdeal_Pages_Per_Visit
0,2012,10,6,50,55,3.0,2.5,4.5,3.2
1,2012,10,6,50,55,3.0,2.5,4.5,3.2
2,2013,25,15,48,54,3.4,2.6,4.8,3.4
3,2014,55,40,47,53,3.6,2.7,5.0,3.6
4,2015,95,60,46,52,3.7,2.8,5.2,3.7
5,2016,120,50,44,55,3.9,2.6,5.4,3.5
6,2017,135,25,43,57,4.0,2.3,5.6,3.2
7,2018,150,15,42,58,4.1,2.1,5.7,3.0
8,2019,180,10,41,59,4.3,2.0,5.9,2.9
9,2020,250,8,40,60,4.5,1.9,6.0,2.8
10,2021,270,7,39,61,4.6,1.8,6.1,2.7
11,2022,290,6,38,62,4.8,1.7,6.2,2.6
12,2023,310,5,37,63,4.9,1.6,6.3,2.5
13,2024,330,4,36,64,5.0,1.5,6.4,2.4
14,2025,345,3,35,65,5.1,1.4,6.5,2.3

In [2]:
print(df.dtypes)

Year                          int64
Flipkart_Visits_Million       int64
Snapdeal_Visits_Million       int64
Flipkart_Bounce_Rate_%        int64
Snapdeal_Bounce_Rate_%        int64
Flipkart_Avg_Session_Min    float64
Snapdeal_Avg_Session_Min    float64
Flipkart_Pages_Per_Visit    float64
Snapdeal_Pages_Per_Visit    float64
dtype: object

In [35]:

import numpy as np
df=pd.read_csv('Products.csv')
df

,company1,Category,product_count1,Date,company2,product_count2
0,Flipkart,Electronics,395032.0,2025-08-26,Snapdeal,223648.0
1,Flipkart,Tvs&Appliance,61763.0,2025-08-26,Snapdeal,0.0
2,Flipkart,MenFashion,385895.0,2025-08-26,Snapdeal,571294.0
3,Flipkart,WomenFashion,726423.0,2025-08-26,Snapdeal,150802.0
4,Flipkart,Baby&Kids,261356.0,2025-08-26,Snapdeal,138014.0
5,Flipkart,Home&Furniture,535005.0,2025-08-26,Snapdeal,283489.0
6,Flipkart,Sports&Books& More,300602.0,2025-08-26,Snapdeal,109463.0
7,Flipkart,Automatives,0.0,2025-08-26,Snapdeal,70023.0

In [4]:
df=df.rename(columns=({'Company_name ':'company1','Company_name':'company2','product_count':'product_count1','Product_name':'product_count2'}))
df

   company1            Category product_count1  Date  company2 product_count2
0  Flipkart         Electronics         395032   NaN  Snapdeal         223648
1  Flipkart      Tvs&Appliance           61763   NaN  Snapdeal            N/a
2  Flipkart          MenFashion         385895   NaN  Snapdeal         571294
3  Flipkart        WomenFashion         726423   NaN  Snapdeal         150802
4  Flipkart           Baby&Kids         261356   NaN  Snapdeal         138014
5  Flipkart      Home&Furniture         535005   NaN  Snapdeal         283489
6  Flipkart  Sports&Books& More         300602   NaN  Snapdeal         109463
7  Flipkart         Automatives            N/a   NaN  Snapdeal          70023

In [5]:
df=df.astype({'company1':'string','Category':'string','company2':'string'})
df

   company1            Category product_count1  Date  company2 product_count2
0  Flipkart         Electronics         395032   NaN  Snapdeal         223648
1  Flipkart      Tvs&Appliance           61763   NaN  Snapdeal            N/a
2  Flipkart          MenFashion         385895   NaN  Snapdeal         571294
3  Flipkart        WomenFashion         726423   NaN  Snapdeal         150802
4  Flipkart           Baby&Kids         261356   NaN  Snapdeal         138014
5  Flipkart      Home&Furniture         535005   NaN  Snapdeal         283489
6  Flipkart  Sports&Books& More         300602   NaN  Snapdeal         109463
7  Flipkart         Automatives            N/a   NaN  Snapdeal          70023

In [10]:
df['product_count1']=pd.to_numeric(df['product_count1'],errors='coerce')
df['product_count2']=pd.to_numeric(df['product_count2'],errors='coerce')
df.dtypes

company1          string[python]
Category          string[python]
product_count1           float64
Date                     float64
company2          string[python]
product_count2           float64
dtype: object

In [11]:
df=df.replace({"N/a":np.nan})
df['product_count1']=df['product_count1'].fillna(0)
df['product_count2']=df['product_count2'].fillna(0)
df

,company1,Category,product_count1,Date,company2,product_count2
0,Flipkart,Electronics,395032.0,NaN,Snapdeal,223648.0
1,Flipkart,Tvs&Appliance,61763.0,NaN,Snapdeal,0.0
2,Flipkart,MenFashion,385895.0,NaN,Snapdeal,571294.0
3,Flipkart,WomenFashion,726423.0,NaN,Snapdeal,150802.0
4,Flipkart,Baby&Kids,261356.0,NaN,Snapdeal,138014.0
5,Flipkart,Home&Furniture,535005.0,NaN,Snapdeal,283489.0
6,Flipkart,Sports&Books& More,300602.0,NaN,Snapdeal,109463.0
7,Flipkart,Automatives,0.0,NaN,Snapdeal,70023.0

In [27]:
print(list(df.columns))

['company1', 'Category', 'product_count', 'Date', 'company2', 'Product_name']

In [14]:
df['Date']=pd.to_datetime(df['Date'],errors='coerce')
df['Date']=df['Date'].fillna(pd.to_datetime('2025-08-26'))
df

,company1,Category,product_count1,Date,company2,product_count2
0,Flipkart,Electronics,395032.0,2025-08-26,Snapdeal,223648.0
1,Flipkart,Tvs&Appliance,61763.0,2025-08-26,Snapdeal,0.0
2,Flipkart,MenFashion,385895.0,2025-08-26,Snapdeal,571294.0
3,Flipkart,WomenFashion,726423.0,2025-08-26,Snapdeal,150802.0
4,Flipkart,Baby&Kids,261356.0,2025-08-26,Snapdeal,138014.0
5,Flipkart,Home&Furniture,535005.0,2025-08-26,Snapdeal,283489.0
6,Flipkart,Sports&Books& More,300602.0,2025-08-26,Snapdeal,109463.0
7,Flipkart,Automatives,0.0,2025-08-26,Snapdeal,70023.0

In [15]:
df.to_csv('Products.csv',index=False)

In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('playstore_reviews.csv')
df

,userName,content,score,thumbs_up_count,review_version,review_date,reply_content,app_version,company
0,Rituraj Gogoi,Mind blowing,1,0,8.28,11-08-2025,"Hi flipkart user, we sincerely apologize for t...",8.28,Flipkart
1,Sirisha siri Siri,Super gud,5,0,8.29,11-08-2025,"Hi flipkart user, thank you so much for your f...",8.29,Flipkart
2,Afifakhan Khan,Not cash on delivery only online payment,1,0,8.29,11-08-2025,No Reply,8.29,Flipkart
3,Sanjay Yadav,Happy,5,0,8.29,11-08-2025,"Hi flipkart user, thank you so much for your f...",8.29,Flipkart
4,Balendra Singh,Open nhi ho rha hai.,1,0,6.17,11-08-2025,"Hi flipkart user, we sincerely apologize for t...",6.17,Flipkart
...,...,...,...,...,...,...,...,...,...
3995,Rishi Kohli,Good,5,0,8.1.7,16-06-2025,Thanks!,8.1.7,Snapdeal
3996,Rohit Sharma,"Ordered through snapdeal, rider was from ekart...",1,0,Unkown,16-06-2025,Hi rohit! sorry to disappoint you. please shar...,Unknown,Snapdeal
3997,varshini Karthikeyan,Nice delivery app,5,0,8.1.0,16-06-2025,Glad to know that you are happy with our app :),8.1.0,Snapdeal
3998,emran emran,Love,5,0,Unkown,16-06-2025,Thanks a ton!,Unknown,Snapdeal
3999,Manish J,Good material and fast delivery,5,0,8.1.7,16-06-2025,Thanks a lot :-),8.1.7,Snapdeal

In [2]:
df=df.drop(columns=['userImage','reviewId','repliedAt'])
df

KeyError: "['userImage', 'reviewId', 'repliedAt'] not found in axis"

In [72]:
df['userName']=df['userName'].astype('string').str.strip()
df

,userName,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,appVersion,company
0,Rituraj Gogoi,mind blowing,1,0,8.28,2025-08-11 11:11:12,"Hi Flipkart User, We sincerely apologize for t...",8.28,Flipkart
1,Sirisha siri Siri,super gud,5,0,8.29,2025-08-11 11:10:59,"Hi Flipkart User, Thank you so much for your f...",8.29,Flipkart
2,Afifakhan Khan,not cash on delivery only online payment,1,0,8.29,2025-08-11 11:10:11,NaN,8.29,Flipkart
3,Sanjay Yadav,happy,5,0,8.29,2025-08-11 11:10:07,"Hi Flipkart User, Thank you so much for your f...",8.29,Flipkart
4,Balendra Singh,open nhi ho rha hai.,1,0,6.17,2025-08-11 11:09:32,"Hi Flipkart User, We sincerely apologize for t...",6.17,Flipkart
...,...,...,...,...,...,...,...,...,...
3995,Rishi Kohli,good 👍,5,0,8.1.7,2025-06-16 19:00:18,Thanks!,8.1.7,Snapdeal
3996,Rohit Sharma,"ordered through snapdeal, rider was from ekart...",1,0,NaN,2025-06-16 18:55:45,Hi Rohit! Sorry to disappoint you. Please shar...,NaN,Snapdeal
3997,varshini Karthikeyan,nice delivery app,5,0,8.1.0,2025-06-16 18:18:41,Glad to know that you are happy with our App :),8.1.0,Snapdeal
3998,emran emran,love,5,0,NaN,2025-06-16 18:16:03,Thanks a ton!,NaN,Snapdeal
3999,Manish J,good material and fast delivery,5,0,8.1.7,2025-06-16 18:14:48,Thanks a lot :-),8.1.7,Snapdeal

In [3]:
import re
import pandas as pd

# Make sure it's string type
df['content'] = df['content'].astype(str)

# Emoji regex covering most Unicode emojis
emoji_pattern = re.compile(
    "["
    "\U0001F600-\U0001F64F"  # emoticons
    "\U0001F300-\U0001F5FF"  # symbols & pictographs
    "\U0001F680-\U0001F6FF"  # transport & map symbols
    "\U0001F1E0-\U0001F1FF"  # flags
    "\U00002700-\U000027BF"  # dingbats
    "\U0001F900-\U0001F9FF"  # supplemental symbols
    "\U00002600-\U000026FF"  # misc symbols
    "\U00002B00-\U00002BFF"  # arrows etc
    "\U0001FA70-\U0001FAFF"  # new emojis
    "\U000025A0-\U000025FF"  # geometric shapes
    "]+", flags=re.UNICODE
)

# Remove emojis from every row
df['content'] = df['content'].apply(lambda x: emoji_pattern.sub('', x))

# Optional: remove extra spaces left behind
df['content'] = df['content'].str.replace(r'\s+', ' ', regex=True).str.strip()
df

,userName,content,score,thumbs_up_count,review_version,review_date,reply_content,app_version,company
0,Rituraj Gogoi,Mind blowing,1,0,8.28,11-08-2025,"Hi flipkart user, we sincerely apologize for t...",8.28,Flipkart
1,Sirisha siri Siri,Super gud,5,0,8.29,11-08-2025,"Hi flipkart user, thank you so much for your f...",8.29,Flipkart
2,Afifakhan Khan,Not cash on delivery only online payment,1,0,8.29,11-08-2025,No Reply,8.29,Flipkart
3,Sanjay Yadav,Happy,5,0,8.29,11-08-2025,"Hi flipkart user, thank you so much for your f...",8.29,Flipkart
4,Balendra Singh,Open nhi ho rha hai.,1,0,6.17,11-08-2025,"Hi flipkart user, we sincerely apologize for t...",6.17,Flipkart
...,...,...,...,...,...,...,...,...,...
3995,Rishi Kohli,Good,5,0,8.1.7,16-06-2025,Thanks!,8.1.7,Snapdeal
3996,Rohit Sharma,"Ordered through snapdeal, rider was from ekart...",1,0,Unkown,16-06-2025,Hi rohit! sorry to disappoint you. please shar...,Unknown,Snapdeal
3997,varshini Karthikeyan,Nice delivery app,5,0,8.1.0,16-06-2025,Glad to know that you are happy with our app :),8.1.0,Snapdeal
3998,emran emran,Love,5,0,Unkown,16-06-2025,Thanks a ton!,Unknown,Snapdeal
3999,Manish J,Good material and fast delivery,5,0,8.1.7,16-06-2025,Thanks a lot :-),8.1.7,Snapdeal

In [74]:
df=df.rename(columns=({'thumbsUpCount':'thumbs_up_count','reviewCreatedVersion':'review_version','at':'review_date','replyContent':'reply_content','appVersion':'app_version'}))
df

,userName,content,score,thumbs_up_count,review_version,review_date,reply_content,app_version,company
0,Rituraj Gogoi,Mind blowing,1,0,8.28,2025-08-11 11:11:12,"Hi Flipkart User, We sincerely apologize for t...",8.28,Flipkart
1,Sirisha siri Siri,Super gud,5,0,8.29,2025-08-11 11:10:59,"Hi Flipkart User, Thank you so much for your f...",8.29,Flipkart
2,Afifakhan Khan,Not cash on delivery only online payment,1,0,8.29,2025-08-11 11:10:11,NaN,8.29,Flipkart
3,Sanjay Yadav,Happy,5,0,8.29,2025-08-11 11:10:07,"Hi Flipkart User, Thank you so much for your f...",8.29,Flipkart
4,Balendra Singh,Open nhi ho rha hai.,1,0,6.17,2025-08-11 11:09:32,"Hi Flipkart User, We sincerely apologize for t...",6.17,Flipkart
...,...,...,...,...,...,...,...,...,...
3995,Rishi Kohli,Good,5,0,8.1.7,2025-06-16 19:00:18,Thanks!,8.1.7,Snapdeal
3996,Rohit Sharma,"Ordered through snapdeal, rider was from ekart...",1,0,NaN,2025-06-16 18:55:45,Hi Rohit! Sorry to disappoint you. Please shar...,NaN,Snapdeal
3997,varshini Karthikeyan,Nice delivery app,5,0,8.1.0,2025-06-16 18:18:41,Glad to know that you are happy with our App :),8.1.0,Snapdeal
3998,emran emran,Love,5,0,NaN,2025-06-16 18:16:03,Thanks a ton!,NaN,Snapdeal
3999,Manish J,Good material and fast delivery,5,0,8.1.7,2025-06-16 18:14:48,Thanks a lot :-),8.1.7,Snapdeal

In [75]:
df['review_version']=df['review_version'].astype('string').str.strip()
df['review_version']=df['review_version'].replace({"<NA>":"Unknown"}).fillna("Unkown")
print(df['review_version'].dtype)
df

string

,userName,content,score,thumbs_up_count,review_version,review_date,reply_content,app_version,company
0,Rituraj Gogoi,Mind blowing,1,0,8.28,2025-08-11 11:11:12,"Hi Flipkart User, We sincerely apologize for t...",8.28,Flipkart
1,Sirisha siri Siri,Super gud,5,0,8.29,2025-08-11 11:10:59,"Hi Flipkart User, Thank you so much for your f...",8.29,Flipkart
2,Afifakhan Khan,Not cash on delivery only online payment,1,0,8.29,2025-08-11 11:10:11,NaN,8.29,Flipkart
3,Sanjay Yadav,Happy,5,0,8.29,2025-08-11 11:10:07,"Hi Flipkart User, Thank you so much for your f...",8.29,Flipkart
4,Balendra Singh,Open nhi ho rha hai.,1,0,6.17,2025-08-11 11:09:32,"Hi Flipkart User, We sincerely apologize for t...",6.17,Flipkart
...,...,...,...,...,...,...,...,...,...
3995,Rishi Kohli,Good,5,0,8.1.7,2025-06-16 19:00:18,Thanks!,8.1.7,Snapdeal
3996,Rohit Sharma,"Ordered through snapdeal, rider was from ekart...",1,0,Unkown,2025-06-16 18:55:45,Hi Rohit! Sorry to disappoint you. Please shar...,NaN,Snapdeal
3997,varshini Karthikeyan,Nice delivery app,5,0,8.1.0,2025-06-16 18:18:41,Glad to know that you are happy with our App :),8.1.0,Snapdeal
3998,emran emran,Love,5,0,Unkown,2025-06-16 18:16:03,Thanks a ton!,NaN,Snapdeal
3999,Manish J,Good material and fast delivery,5,0,8.1.7,2025-06-16 18:14:48,Thanks a lot :-),8.1.7,Snapdeal

In [76]:
df['review_date']=pd.to_datetime(df['review_date'],errors='coerce')
df['review_date']=df['review_date'].dt.strftime('%d-%m-%Y')
df

,userName,content,score,thumbs_up_count,review_version,review_date,reply_content,app_version,company
0,Rituraj Gogoi,Mind blowing,1,0,8.28,11-08-2025,"Hi Flipkart User, We sincerely apologize for t...",8.28,Flipkart
1,Sirisha siri Siri,Super gud,5,0,8.29,11-08-2025,"Hi Flipkart User, Thank you so much for your f...",8.29,Flipkart
2,Afifakhan Khan,Not cash on delivery only online payment,1,0,8.29,11-08-2025,NaN,8.29,Flipkart
3,Sanjay Yadav,Happy,5,0,8.29,11-08-2025,"Hi Flipkart User, Thank you so much for your f...",8.29,Flipkart
4,Balendra Singh,Open nhi ho rha hai.,1,0,6.17,11-08-2025,"Hi Flipkart User, We sincerely apologize for t...",6.17,Flipkart
...,...,...,...,...,...,...,...,...,...
3995,Rishi Kohli,Good,5,0,8.1.7,16-06-2025,Thanks!,8.1.7,Snapdeal
3996,Rohit Sharma,"Ordered through snapdeal, rider was from ekart...",1,0,Unkown,16-06-2025,Hi Rohit! Sorry to disappoint you. Please shar...,NaN,Snapdeal
3997,varshini Karthikeyan,Nice delivery app,5,0,8.1.0,16-06-2025,Glad to know that you are happy with our App :),8.1.0,Snapdeal
3998,emran emran,Love,5,0,Unkown,16-06-2025,Thanks a ton!,NaN,Snapdeal
3999,Manish J,Good material and fast delivery,5,0,8.1.7,16-06-2025,Thanks a lot :-),8.1.7,Snapdeal

In [79]:
df['reply_content']=df['reply_content'].astype('string').str.capitalize().str.strip().fillna("No Reply")
df

,userName,content,score,thumbs_up_count,review_version,review_date,reply_content,app_version,company
0,Rituraj Gogoi,Mind blowing,1,0,8.28,11-08-2025,"Hi flipkart user, we sincerely apologize for t...",8.28,Flipkart
1,Sirisha siri Siri,Super gud,5,0,8.29,11-08-2025,"Hi flipkart user, thank you so much for your f...",8.29,Flipkart
2,Afifakhan Khan,Not cash on delivery only online payment,1,0,8.29,11-08-2025,No Reply,8.29,Flipkart
3,Sanjay Yadav,Happy,5,0,8.29,11-08-2025,"Hi flipkart user, thank you so much for your f...",8.29,Flipkart
4,Balendra Singh,Open nhi ho rha hai.,1,0,6.17,11-08-2025,"Hi flipkart user, we sincerely apologize for t...",6.17,Flipkart
...,...,...,...,...,...,...,...,...,...
3995,Rishi Kohli,Good,5,0,8.1.7,16-06-2025,Thanks!,8.1.7,Snapdeal
3996,Rohit Sharma,"Ordered through snapdeal, rider was from ekart...",1,0,Unkown,16-06-2025,Hi rohit! sorry to disappoint you. please shar...,NaN,Snapdeal
3997,varshini Karthikeyan,Nice delivery app,5,0,8.1.0,16-06-2025,Glad to know that you are happy with our app :),8.1.0,Snapdeal
3998,emran emran,Love,5,0,Unkown,16-06-2025,Thanks a ton!,NaN,Snapdeal
3999,Manish J,Good material and fast delivery,5,0,8.1.7,16-06-2025,Thanks a lot :-),8.1.7,Snapdeal

In [82]:
df['app_version']=df['app_version'].astype('string').str.strip().replace({"<NA>":"Unknown"}).fillna("Unknown")
df['company']=df['company'].astype('string').str.strip()
print(df.dtypes)
df.to_csv('playstore_reviews.csv',index=False)

userName           string[python]
content            string[python]
score                       int64
thumbs_up_count             int64
review_version     string[python]
review_date                object
reply_content      string[python]
app_version        string[python]
company            string[python]
dtype: object